// Bowie — preset Tailwind / NativeWind. Uso: presets: [require('./design/tokens/tailwind.preset.js')]
// As cores semânticas apontam para as variáveis CSS de tokens.css (claro/escuro automáticos).
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        brand: {
          'night': '#1D2B45',
          'bowie-blue': '#6FA8DC',
          'chestnut': '#9A6440',
          'merle': '#8C97A6',
          'smile': '#EE8E98',
          'mist': '#F4F6F8',
          'white': '#FFFFFF',
          'bowie-blue-strong': '#2F6FA8',
          'chestnut-strong': '#7A4C2E',
        },
        neutral: {
          900: '#0F1626',
          800: '#1D2B45',
          700: '#2E3A52',
          600: '#4A5670',
          500: '#5A6782',
          400: '#8C97A6',
          300: '#C3CBD6',
          200: '#DDE2E8',
          100: '#EDF0F4',
          50: '#F4F6F8',
          0: '#FFFFFF',
        },
        'background': 'var(--color-background)',
        'surface': 'var(--color-surface)',
        'surface-muted': 'var(--color-surface-muted)',
        'border': 'var(--color-border)',
        'text': 'var(--color-text)',
        'text-muted': 'var(--color-text-muted)',
        'text-subtle': 'var(--color-text-subtle)',
        'text-on-primary': 'var(--color-text-on-primary)',
        'primary': 'var(--color-primary)',
        'primary-pressed': 'var(--color-primary-pressed)',
        'accent': 'var(--color-accent)',
        'text-on-accent': 'var(--color-text-on-accent)',
        'link': 'var(--color-link)',
        'focus-ring': 'var(--color-focus-ring)',
        'success': 'var(--color-success)',
        'success-soft': 'var(--color-success-soft)',
        'warning': 'var(--color-warning)',
        'warning-soft': 'var(--color-warning-soft)',
        'danger': 'var(--color-danger)',
        'danger-soft': 'var(--color-danger-soft)',
        'info': 'var(--color-info)',
        'info-soft': 'var(--color-info-soft)',
        'category-vaccines': 'var(--category-vaccines)',
        'category-shopping': 'var(--category-shopping)',
        'category-incidents': 'var(--category-incidents)',
      },
      fontFamily: { brand: ['Figtree', 'Nunito Sans', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'] },
      fontSize: {
        'display': ['34px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'title1': ['28px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '800' }],
        'title2': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '800' }],
        'title3': ['18px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'body': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-strong': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'callout': ['15px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'caption': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'overline': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '600' }],
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '18px',
        xl: '28px',
      },
      boxShadow: {
        card: '0 1px 2px rgba(29,43,69,0.06), 0 4px 12px rgba(29,43,69,0.06)',
        sheet: '0 -2px 6px rgba(29,43,69,0.06), 0 -12px 32px rgba(29,43,69,0.10)',
      },
      minHeight: { touch: '44px' },
      minWidth: { touch: '44px' },
    },
  },
};
